# -*- coding: utf-8 -*-
"""Housing Vouchers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ifeNKVQPTQW9RTxpYgdttOysuvvBrjYf
"""

import math
import statistics
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

df = pd.read_excel("/content/FY22_FMRs.xlsx")

df.rename(columns={'fmr_0': 'Effciency Rate', 'fmr_1': '1 Bedroom', 'fmr_2' : '2 Bedroom', 'fmr_3': '3 Bedroom', 'fmr_4' : '4 Bedroom', 'pop2017' : 'Population (2017)'}, inplace=True)

columnEffR = df['Effciency Rate']
column1Bed = df['1 Bedroom']
column2Bed = df['2 Bedroom']
column3Bed = df['3 Bedroom']
column4Bed = df['4 Bedroom']
columnPop = df['Population (2017)']
housingUnits = columnPop / 4.5
expectedIncome = (columnEffR / 0.3)

meanEffR = columnEffR.mean()
mean1Bed = column1Bed.mean()
mean2Bed = column2Bed.mean()
mean3Bed = column3Bed.mean()
mean4Bed = column4Bed.mean()

deltaRent = column1Bed - columnEffR 
meanDeltaRent = deltaRent.mean()

#plt.scatter(columnPop, columnEffR , color="b")
#plt.scatter(columnPop, columnEffR , color="r")

plt.scatter(housingUnits, deltaRent , color="g")